repos:
  - repo: local
    hooks:
      - id: nbdev-docs
        name: Generate website
        entry: bash -c 'if [[ $(git branch --show-current) == "main" ]]; then echo "Running on main branch - generating docs..." && uv run nbdev_docs && git add _docs/; else echo "Not on main branch, skipping docs generation"; fi'
        language: system
        stages: [pre-commit]
        pass_filenames: false
        always_run: true