project:
  type: website
  output-dir: docs
  resources:
    - "CNAME"
    - "resources/"

bibliography:
  - "references.bib"
csl: ieee.csl  # Or use a built-in style
cite-method: citeproc

format:
  html:
    page-layout: full

    theme: 
      light: [flatly, styles/custom-light.scss]
      dark: [darkly, styles/custom-dark.scss]
    css: styles/styles.css
    toc: true
    keep-md: true
    keep-ipynb: true
  commonmark: default

website:
  twitter-card: true
  open-graph: true
  reader-mode: false
  page-navigation: true
  bread-crumbs: false
  favicon: /img/favicon_io/favicon.ico
  repo-url: https://github.com/bhoov/amtutorial
  repo-actions: [issue]
  navbar:
    logo: img/favicon_io/android-chrome-512x512.png
    tools:
      - icon: github
        href: https://github.com/bhoov/amtutorial
  sidebar:
    style: floating

metadata-files: [nbdev.yml, sidebar.yml]
language: 
  title-block-author-single: "Author"
  title-block-author-plural: "Authors"