---
authors: 
    - name: Dmitry Krotov
      email: krotov@ibm.com
      affiliations: IBM Research, MIT
    - name: Benjamin Hoover
      email: bhoov@gatech.edu
      affiliations: IBM Research, Georgia Tech
    - name: Parikshit Ram
      email: parikshit.ram@ibm.com
      affiliations: IBM Research
---

# Tutorial on Modern Methods in Associative Memory
> A complete introduction to Associative Memories and Hopfield Networks for the Modern AI Era

## Getting started

*Commits to the main branch will automatically build the docs website*. Develop in feature branches, merge to main for deployment.

We have tried to streamline the installation of the repo as much as possible.

### Pre-requisites

- Install [`quarto`](https://quarto.org/docs/download/)
- Install [`uv`](https://docs.astral.sh/uv/getting-started/installation/) using `curl -LsSf https://astral.sh/uv/install.sh | sh`
- We use [`conda`](https://www.anaconda.com/docs/getting-started/miniconda/install) (or better yet, [`mamba`](https://github.com/conda-forge/miniforge)) for managing the `ffmpeg` dependency, which only matters if `ffmpeg` is not already installed on your system.

### Setting up the environment

From the root of the repo:

```sh
uv sync
source .venv/bin/activate
uv run ipython kernel install --user --env VIRTUAL_ENV $(pwd)/.venv --name=amtutorial # Expose venv to ipython

# OPTIONAL: For rendering videos in notebooks
conda install conda-forge::ffmpeg conda-forge::openh264 

# OPTIONAL: For developing the interactive frontend
conda install conda-forge::nodejs
npm install --prefix javascript && npm run build --prefix javascript 
```

The first time you run the notebooks will be slow -- we do some initial preprocessing for caching long-running code.

You can view a local version of the website with 

```
uv run nbdev_preview
```

## Deploying

Deploy to `tutorial.amemory.net` by pushing commits to the `main` branch after building the site locally.

```sh
uv run nbdev_export && uv run nbdev_docs && git add . && git commit -m "Update site" && git push
```