# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/amtutorial',
                'doc_host': 'https://bhoov.github.io',
                'git_url': 'https://github.com/bhoov/amtutorial',
                'lib_path': 'amtutorial'},
  'syms': {'amtutorial.core': {'amtutorial.core.foo': ('core.html#foo', 'amtutorial/core.py')}}}
